### ISSUE TITLE
convert subscribe-model.conf files from CSV

### ISSUE THREAD

**Issue by zonca** [tmt-icd/IRIS-Model-Files#26]
`subscribe-model.conf` files have a format which is complex to manipulate both manually and programmatically.

what about having instead a standard CSV with a row for each item and columns 'subsystem', 'component', 'name', 'requiredRate', 'usage' and then have a script that can assemble a `subscribe-model.conf` file automatically?

**Comment by edwardchapin** [comment]
I agree, they are not the easiest things to work with directly. TMT is using mongodb to store the data from the model files, so one option would be to write a nicer client for working with the database. Alternatively it would probably be trivial to write a simple CSV<->HOCON converter in Python (we've already been using Python scripts to scrape the model files directly to auto-generate content for technical notes).

**Comment by kgillies** [comment]
I think you make a good point.  When we started this we didn't really know where/how it would go.  We were modeling our effort after the GMT work that used a Coffeescript-based DSL.  We wanted to have a full-up DSL too, but ended up with JSON, and it's a poor substitute. Allan and I have discussed alternatives several times, but were worried about changes. Maybe all the model files could be replaced by one or more spreadsheets.  I don't see a whole lot of value from using JSON at this time other than it's easily digested by the tools we've chosen for ICD-DB.  We will discuss this internally or maybe if you have more ideas add them here?

**Comment by abrighton** [comment]
The model files are in HOCON format, which can be easily converted to JSON, if that helps.
The subscribe-model.conf file is simpler than the publish-model.conf file, which also has to define attributes.

**Comment by zonca** [comment]
I think it would be best to have just a CSV file in this repository that can be easily imported / exported from spreadsheets (github also has a nice search functionality for CSV https://help.github.com/en/github/managing-files-in-a-repository/rendering-csv-and-tsv-data). Then a conversion tool that turns that to HOCON when necessary.

**Comment by zonca** [comment]
so what about having a CSV file and a conversion script?

**Comment by tnakamot** [comment]
If you have a spreadsheet why don't you put it in the repository and convert it directly to HOCON (or JSON) with a macro or a script? I guess you would want to keep some annotation (e.g. note, color) in that spreadsheet which the CSV does not support. I know you have a spreadsheet listing all metadata you want to get with some nice color. I guess everybody wants to see the same thing in the original spreadsheet format.

I am a little bit against of using CSV file instead of HOCON just for subscribe-model.conf. CSV is not suitable to edit in a text editor if one line gets long. I am editing all model files in a text editor and I do not want to use different tools and formats only for subscribe-model.conf. Many assemblies I am designing will have little amount of events to subscribe and HOCON does the job.

**Comment by edwardchapin** [comment]
It wouldn't be unreasonable to have a conversion script for specific cases where it is useful (namely the DRS). It would be up to us to manage the fact that the .csv file is the upstream "true" source of information and the the model files in this repo are simply a rendering. For other cases (mechanism interfaces) we just stick to using the existing HOCON.

**Comment by zonca** [comment]
@tnakamot this is a great idea!

We can:

* keep the "true" upstream source on a Google Sheets
* have a script that [exports a CSV programmatically](https://stackoverflow.com/questions/33713084/download-link-for-google-spreadsheets-csv-export-with-multiple-sheets) and converts to HOCON
* commit HOCON to this repo
* HOCON has link to Google Sheet and notice never to edit it directly

Anyone has other suggestions? otherwise I'll work on a PR for this

**Comment by tnakamot** [comment]
@zonca I think that's the way to go for now.

@kgillies @abrighton, for similar requests which may come up from IRIS and other subsystems, maybe icd-db command can be implemented to call a user script in the directory to generate model files from whatever sources (e.g. google spreadsheet, CSV) so that the model files in HOCON are always up-to-date. It helps the situation not only the DRS that @zonca is currently in, but also will help me

- define commands and status events that are common to some assemblies (IRIS assemblies for mechanisms have defined common patterns, but I hate to copy & paste them for every assembly)
- repeat the same data structure for different attribute names
- define status events from the list of PLC tags (this is not for IRIS, but other subsystems in TMT)

**Comment by abrighton** [comment]
There is already a JIRA issue for reusing data structures: https://tmt-project.atlassian.net/secure/RapidBoard.jspa?rapidView=97&modal=detail&selectedIssue=DEOPSICDDB-99. I'm looking into that.

**Comment by tnakamot** [comment]
@abrighton thanks for looking into that ticket in JIRA. When I filed the JIRA ticket, I thought of a reference to another data structure to represent the repeat of the same data structure, something similar to JSON Schema. My idea here is that a user-defined script may help us define not only such repeated data structures but also create model files from various kinds of sources like a spreadsheet. I guess executing a user-defined script as a part of data ingestion will provide maximum flexibility to respond to various needs from different subsystems with minimal changes in the code of the icddb tools.

**Comment by zonca** [comment]
ok, I'll wait for #24 to be merged and then create the Google Sheet and the script.

**Comment by zonca** [comment]
@arunsurya77 have you already implemented a conversion from Google Sheet to HOCON? If so, can you share the script you created?

**Comment by arunsurya77** [comment]
Hi Andrea ,
I have uploaded the scripts in the
https://github.com/oirlab/iris_icd_tool repo
It's a very basic script at this point and expects the repos to be already
cloned as subdirectories in the same directory.
Cheers
Arun

**Comment by zonca** [comment]
@arunsurya77 is the script updated with the last changes in #24?
can you please give me permissions on the Google Doc so I can edit it?

**Comment by arunsurya77** [comment]
Hi Andrea , I have shared the google sheet  which reflects the subscription in #24 . There is some work needed to connect this with the fits headers. I will look into it.

**Comment by zonca** [comment]
ok, this is implemented in the https://github.com/oirlab/iris_metadata repository
