### ISSUE TITLE
Events vs Telemetry

### ISSUE THREAD

**Issue by zonca** [tmt-icd/IRIS-Model-Files#27]
I see that there are events like `readoutFailed`:

https://github.com/tmt-icd/IRIS-Model-Files/blob/master/drs/drs-assembly/subscribe-model.conf#L1659-L1663

and that now all the telemetry is also under `events` (it used to be under `telemetry` in the past), I see @arunsurya77 made this change in https://github.com/tmt-icd/IRIS-Model-Files/commit/a9a5009fb9a768798e26b873e22458fbaa34375d.

Shouldn't there be a separation between what is telemetry and what are events?

**Comment by zonca** [comment]
actually `events` is defined twice, so the file is broken, in fact if I try to load it with `pyhocon`, the second definition of `events` at line 1627 overwrites the first at line 13, so I only have the last 13 elements instead of the >200 I should have.

**Comment by arunsurya77** [comment]
Okay that must have been a mistake. Since all telemetry is now events I made that change to get icd-tools to operate on DRS ICD file.  WIll correct the multiple events definition.

**Comment by zonca** [comment]
any news on a fix for this?

**Comment by edwardchapin** [comment]
Looks to have been fixed already in 983d08e8accdc396aaba2bb3e4e111c1d629d93f . I think you can close this PR.

**Comment by zonca** [comment]
so there is no more `telemetry` section? is that expected?

**Comment by zonca** [comment]
also, shouldn't we do pull requests, assign a reviewer, and make a quick crosscheck of changes made to master?

**Comment by edwardchapin** [comment]
Correct: there were separate Telemetry and Event services in earlier CSW prototypes built on different back-end technologies. Ultimately through the CCR process it was decided to merge the two services into one, thus deprecating the Telemetry blocks in the model file schema.

**Comment by edwardchapin** [comment]
re PRs: yes, should probably have been handled with this existing PR. Note that I'm not personally opposed to people pushing to master directly for the time being because I'd like to encourage people to push their work with as little friction as possible. My thought was to enforce master branch protection towards the end of the final design phase and then switch to a full PR + review + merge workflow then.

Point taken though - unless you were actively monitoring the master branch, you wouldn't have noticed that this issue you raised had already been fixed.

**Comment by zonca** [comment]
ok,
with the web interface is very easy to do a PR, we should never bypass that.
